=== svinchon/WellnessProgramXPression/xDWTemplates/MonthlyReportXQResult.xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="MonthlyReports">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="MonthlyReport"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MonthlyReport">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="badge_number"/>
        <xs:element ref="email"/>
        <xs:element ref="first_name"/>
        <xs:element ref="last_name"/>
        <xs:element ref="gender"/>
        <xs:element ref="update_date"/>
        <xs:element ref="first_date"/>
        <xs:element ref="award_threshold"/>
        <xs:element ref="days_above_threshold"/>
        <xs:element ref="award"/>
        <xs:element ref="index_history_items"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="badge_number" type="xs:integer"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="first_name" type="xs:NCName"/>
  <xs:element name="last_name" type="xs:NCName"/>
  <xs:element name="gender" type="xs:NCName"/>
  <xs:element name="update_date" type="xs:NMTOKEN"/>
  <xs:element name="first_date" type="xs:NMTOKEN"/>
  <xs:element name="award_threshold" type="xs:integer"/>
  <xs:element name="days_above_threshold" type="xs:integer"/>
  <xs:element name="award" type="xs:boolean"/>
  <xs:element name="index_history_items">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="index_history_item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="index_history_item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="day_offset"/>
        <xs:element ref="date"/>
        <xs:element ref="value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="day_offset" type="xs:integer"/>
  <xs:element name="date" type="xs:NMTOKEN"/>
  <xs:element name="value" type="xs:integer"/>
</xs:schema>

=== svinchon/WellnessProgramXPression/xDWTemplates/MonthlyReportXQResult.xml
<?xml version="1.0"?>
<MonthlyReports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MonthlyReportXQResult.xml.xsd">
  <MonthlyReport>
    <badge_number>123456</badge_number>
    <email>svinchon@corp.com</email>
    <first_name>Sebastien</first_name>
    <last_name>Vinchon</last_name>
    <gender>male</gender>
    <update_date>2015-02-15</update_date>
    <first_date>2015-01-18</first_date>
    <award_threshold>300</award_threshold>
    <days_above_threshold>1</days_above_threshold>
    <award>false</award>
    <index_history_items>
      <index_history_item>
        <day_offset>1</day_offset>
        <date>2015-01-19</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>2</day_offset>
        <date>2015-01-20</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>3</day_offset>
        <date>2015-01-21</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>4</day_offset>
        <date>2015-01-22</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>5</day_offset>
        <date>2015-01-23</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>6</day_offset>
        <date>2015-01-24</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>7</day_offset>
        <date>2015-01-25</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>8</day_offset>
        <date>2015-01-26</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>9</day_offset>
        <date>2015-01-27</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>10</day_offset>
        <date>2015-01-28</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>11</day_offset>
        <date>2015-01-29</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>12</day_offset>
        <date>2015-01-30</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>13</day_offset>
        <date>2015-01-31</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>14</day_offset>
        <date>2015-02-01</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>15</day_offset>
        <date>2015-02-02</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>16</day_offset>
        <date>2015-02-03</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>17</day_offset>
        <date>2015-02-04</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>18</day_offset>
        <date>2015-02-05</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>19</day_offset>
        <date>2015-02-06</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>20</day_offset>
        <date>2015-02-07</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>21</day_offset>
        <date>2015-02-08</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>22</day_offset>
        <date>2015-02-09</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>23</day_offset>
        <date>2015-02-10</date>
        <value>150</value>
      </index_history_item>
      <index_history_item>
        <day_offset>24</day_offset>
        <date>2015-02-11</date>
        <value>250</value>
      </index_history_item>
      <index_history_item>
        <day_offset>25</day_offset>
        <date>2015-02-12</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>26</day_offset>
        <date>2015-02-13</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>27</day_offset>
        <date>2015-02-14</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>28</day_offset>
        <date>2015-02-15</date>
        <value>0</value>
      </index_history_item>
    </index_history_items>
  </MonthlyReport>
  <MonthlyReport>
    <badge_number>123457</badge_number>
    <email>svinchon@corp.com</email>
    <first_name>Dmitry</first_name>
    <last_name>Etin</last_name>
    <gender>male</gender>
    <update_date>2015-02-15</update_date>
    <first_date>2015-01-18</first_date>
    <award_threshold>300</award_threshold>
    <days_above_threshold>0</days_above_threshold>
    <award>false</award>
    <index_history_items>
      <index_history_item>
        <day_offset>1</day_offset>
        <date>2015-01-19</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>2</day_offset>
        <date>2015-01-20</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>3</day_offset>
        <date>2015-01-21</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>4</day_offset>
        <date>2015-01-22</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>5</day_offset>
        <date>2015-01-23</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>6</day_offset>
        <date>2015-01-24</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>7</day_offset>
        <date>2015-01-25</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>8</day_offset>
        <date>2015-01-26</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>9</day_offset>
        <date>2015-01-27</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>10</day_offset>
        <date>2015-01-28</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>11</day_offset>
        <date>2015-01-29</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>12</day_offset>
        <date>2015-01-30</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>13</day_offset>
        <date>2015-01-31</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>14</day_offset>
        <date>2015-02-01</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>15</day_offset>
        <date>2015-02-02</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>16</day_offset>
        <date>2015-02-03</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>17</day_offset>
        <date>2015-02-04</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>18</day_offset>
        <date>2015-02-05</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>19</day_offset>
        <date>2015-02-06</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>20</day_offset>
        <date>2015-02-07</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>21</day_offset>
        <date>2015-02-08</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>22</day_offset>
        <date>2015-02-09</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>23</day_offset>
        <date>2015-02-10</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>24</day_offset>
        <date>2015-02-11</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>25</day_offset>
        <date>2015-02-12</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>26</day_offset>
        <date>2015-02-13</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>27</day_offset>
        <date>2015-02-14</date>
        <value>0</value>
      </index_history_item>
      <index_history_item>
        <day_offset>28</day_offset>
        <date>2015-02-15</date>
        <value>0</value>
      </index_history_item>
    </index_history_items>
  </MonthlyReport>
</MonthlyReports>
