=== svinchon/WellnessProgramXPression/xDWTemplates/zMonthlyReport/MonthlyReportXQResult.xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="MonthlyReports">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="MonthlyReport"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MonthlyReport">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="badge_number"/>
        <xs:element ref="email"/>
        <xs:element ref="first_name"/>
        <xs:element ref="last_name"/>
        <xs:element ref="gender"/>
        <xs:element ref="update_date"/>
        <xs:element ref="first_date"/>
        <xs:element ref="award_threshold"/>
        <xs:element ref="days_above_threshold"/>
        <xs:element ref="award"/>
        <xs:element ref="index_history_nvp"/>
        <xs:element ref="index_history_csv"/>
        <xs:element ref="index_history_xml"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="badge_number" type="xs:integer"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="first_name" type="xs:NCName"/>
  <xs:element name="last_name" type="xs:NCName"/>
  <xs:element name="gender" type="xs:NCName"/>
  <xs:element name="update_date" type="xs:NMTOKEN"/>
  <xs:element name="first_date" type="xs:NMTOKEN"/>
  <xs:element name="award_threshold" type="xs:integer"/>
  <xs:element name="days_above_threshold" type="xs:integer"/>
  <xs:element name="award" type="xs:boolean"/>
  <xs:element name="index_history_nvp" type="xs:string"/>
  <xs:element name="index_history_csv" type="xs:string"/>
  <xs:element name="index_history_xml" type="xs:string"/>
</xs:schema>

=== svinchon/WellnessProgramXPression/xDWTemplates/zMonthlyReport/MonthlyReportXQResult.xml
<?xml version="1.0"?>
<MonthlyReports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MonthlyReportXQResult.xml.xsd">
  <MonthlyReport>
    <badge_number>123456</badge_number>
    <email>svinchon@corp.com</email>
    <first_name>Sebastien</first_name>
    <last_name>Vinchon</last_name>
    <gender>male</gender>
    <update_date>2015-02-15</update_date>
    <first_date>2015-01-18</first_date>
    <award_threshold>300</award_threshold>
    <days_above_threshold>3</days_above_threshold>
    <award>true</award>
    <index_history_nvp>2015-01-19=0;2015-01-20=0;2015-01-21=0;2015-01-22=0;2015-01-23=0;2015-01-24=0;2015-01-25=0;2015-01-26=0;2015-01-27=0;2015-01-28=0;2015-01-29=0;2015-01-30=0;2015-01-31=0;2015-02-01=0;2015-02-02=0;2015-02-03=0;2015-02-04=0;2015-02-05=0;2015-02-06=0;2015-02-07=0;2015-02-08=0;2015-02-09=0;2015-02-10=450;2015-02-11=350;2015-02-12=350;2015-02-13=200;2015-02-14=100;2015-02-15=0</index_history_nvp>
    <index_history_csv>Categories;2015-01-19;2015-01-20;2015-01-21;2015-01-22;2015-01-23;2015-01-24;2015-01-25;2015-01-26;2015-01-27;2015-01-28;2015-01-29;2015-01-30;2015-01-31;2015-02-01;2015-02-02;2015-02-03;2015-02-04;2015-02-05;2015-02-06;2015-02-07;2015-02-08;2015-02-09;2015-02-10;2015-02-11;2015-02-12;2015-02-13;2015-02-14;2015-02-15#Serie 1;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;450;350;350;200;100;0</index_history_csv>
    <index_history_xml>&lt;chart_data>&lt;categories>&lt;title>Date&lt;/title>&lt;values>&lt;value>2015-01-19&lt;/value>&lt;value>2015-01-20&lt;/value>&lt;value>2015-01-21&lt;/value>&lt;value>2015-01-22&lt;/value>&lt;value>2015-01-23&lt;/value>&lt;value>2015-01-24&lt;/value>&lt;value>2015-01-25&lt;/value>&lt;value>2015-01-26&lt;/value>&lt;value>2015-01-27&lt;/value>&lt;value>2015-01-28&lt;/value>&lt;value>2015-01-29&lt;/value>&lt;value>2015-01-30&lt;/value>&lt;value>2015-01-31&lt;/value>&lt;value>2015-02-01&lt;/value>&lt;value>2015-02-02&lt;/value>&lt;value>2015-02-03&lt;/value>&lt;value>2015-02-04&lt;/value>&lt;value>2015-02-05&lt;/value>&lt;value>2015-02-06&lt;/value>&lt;value>2015-02-07&lt;/value>&lt;value>2015-02-08&lt;/value>&lt;value>2015-02-09&lt;/value>&lt;value>2015-02-10&lt;/value>&lt;value>2015-02-11&lt;/value>&lt;value>2015-02-12&lt;/value>&lt;value>2015-02-13&lt;/value>&lt;value>2015-02-14&lt;/value>&lt;value>2015-02-15&lt;/value>&lt;/values>&lt;/categories>&lt;series>&lt;serie>&lt;title>Index&lt;/title>&lt;values>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>450&lt;/value>&lt;value>350&lt;/value>&lt;value>350&lt;/value>&lt;value>200&lt;/value>&lt;value>100&lt;/value>&lt;value>0&lt;/value>&lt;/values>&lt;/serie>&lt;/series>&lt;/chart_data></index_history_xml>
  </MonthlyReport>
  <MonthlyReport>
    <badge_number>123457</badge_number>
    <email>svinchon@corp.com</email>
    <first_name>Dmitry</first_name>
    <last_name>Etin</last_name>
    <gender>male</gender>
    <update_date>2015-02-15</update_date>
    <first_date>2015-01-18</first_date>
    <award_threshold>300</award_threshold>
    <days_above_threshold>0</days_above_threshold>
    <award>false</award>
    <index_history_nvp>2015-01-19=0;2015-01-20=0;2015-01-21=0;2015-01-22=0;2015-01-23=0;2015-01-24=0;2015-01-25=0;2015-01-26=0;2015-01-27=0;2015-01-28=0;2015-01-29=0;2015-01-30=0;2015-01-31=0;2015-02-01=0;2015-02-02=0;2015-02-03=0;2015-02-04=0;2015-02-05=0;2015-02-06=0;2015-02-07=0;2015-02-08=0;2015-02-09=0;2015-02-10=0;2015-02-11=0;2015-02-12=0;2015-02-13=0;2015-02-14=100;2015-02-15=0</index_history_nvp>
    <index_history_csv>Categories;2015-01-19;2015-01-20;2015-01-21;2015-01-22;2015-01-23;2015-01-24;2015-01-25;2015-01-26;2015-01-27;2015-01-28;2015-01-29;2015-01-30;2015-01-31;2015-02-01;2015-02-02;2015-02-03;2015-02-04;2015-02-05;2015-02-06;2015-02-07;2015-02-08;2015-02-09;2015-02-10;2015-02-11;2015-02-12;2015-02-13;2015-02-14;2015-02-15#Serie 1;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;100;0</index_history_csv>
    <index_history_xml>&lt;chart_data>&lt;categories>&lt;title>Date&lt;/title>&lt;values>&lt;value>2015-01-19&lt;/value>&lt;value>2015-01-20&lt;/value>&lt;value>2015-01-21&lt;/value>&lt;value>2015-01-22&lt;/value>&lt;value>2015-01-23&lt;/value>&lt;value>2015-01-24&lt;/value>&lt;value>2015-01-25&lt;/value>&lt;value>2015-01-26&lt;/value>&lt;value>2015-01-27&lt;/value>&lt;value>2015-01-28&lt;/value>&lt;value>2015-01-29&lt;/value>&lt;value>2015-01-30&lt;/value>&lt;value>2015-01-31&lt;/value>&lt;value>2015-02-01&lt;/value>&lt;value>2015-02-02&lt;/value>&lt;value>2015-02-03&lt;/value>&lt;value>2015-02-04&lt;/value>&lt;value>2015-02-05&lt;/value>&lt;value>2015-02-06&lt;/value>&lt;value>2015-02-07&lt;/value>&lt;value>2015-02-08&lt;/value>&lt;value>2015-02-09&lt;/value>&lt;value>2015-02-10&lt;/value>&lt;value>2015-02-11&lt;/value>&lt;value>2015-02-12&lt;/value>&lt;value>2015-02-13&lt;/value>&lt;value>2015-02-14&lt;/value>&lt;value>2015-02-15&lt;/value>&lt;/values>&lt;/categories>&lt;series>&lt;serie>&lt;title>Index&lt;/title>&lt;values>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>0&lt;/value>&lt;value>100&lt;/value>&lt;value>0&lt;/value>&lt;/values>&lt;/serie>&lt;/series>&lt;/chart_data></index_history_xml>
  </MonthlyReport>
</MonthlyReports>
