=== svinchon/WellnessProgramXPression/xDWTemplates/zWeeklyReport/WeeklyReportXQResult.xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="WeeklyReports">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="WeeklyReport"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="WeeklyReport">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="badge_number"/>
        <xs:element ref="email"/>
        <xs:element ref="first_name"/>
        <xs:element ref="last_name"/>
        <xs:element ref="gender"/>
        <xs:element ref="week_start_date"/>
        <xs:element ref="recomendations"/>
        <xs:element ref="index_history_nvp"/>
        <xs:element ref="index_history_csv"/>
        <xs:element ref="index_history_xml"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="badge_number" type="xs:integer"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="first_name" type="xs:NCName"/>
  <xs:element name="last_name" type="xs:NCName"/>
  <xs:element name="gender" type="xs:NCName"/>
  <xs:element name="week_start_date" type="xs:NMTOKEN"/>
  <xs:element name="recomendations">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="recomendation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="recomendation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="value"/>
        <xs:element ref="label"/>
        <xs:element ref="color"/>
        <xs:element ref="text"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="value" type="xs:integer"/>
  <xs:element name="label" type="xs:NCName"/>
  <xs:element name="color" type="xs:string"/>
  <xs:element name="text" type="xs:string"/>
  <xs:element name="index_history_nvp" type="xs:string"/>
  <xs:element name="index_history_csv" type="xs:string"/>
  <xs:element name="index_history_xml" type="xs:string"/>
</xs:schema>

=== svinchon/WellnessProgramXPression/xDWTemplates/zWeeklyReport/WeeklyReportXQResult.xml
<?xml version="1.0"?>
<WeeklyReports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WeeklyReportXQResult.xml.xsd">
	<WeeklyReport>
		<badge_number>123456</badge_number>
		<email>svinchon@corp.com</email>
		<first_name>Sebastien</first_name>
		<last_name>Vinchon</last_name>
		<gender>male</gender>
		<week_start_date>2015-02-09</week_start_date>
		<recomendations>
			<recomendation>
				<!-- 0 to N occurrences -->
				<value>80</value>
				<!-- percentage, can be more than 100% => if so template charts need to be adjusted -->
				<label>Steps</label>
				<color>RGB value</color>
				<!-- it currently take an hex value like FF2200 but it seems to me that it would make more sense to let the choice be made at the template level or and indicator should also be provided to change the background image -->
				<text>Do more steps</text>
			</recomendation>
			<recomendation>
				<value>100</value>
				<label>Water</label>
				<color>RGB value</color>
				<text>Water drinking was great</text>
				<!-- did you mean "keep drinking the same way"?  -->
			</recomendation>
		</recomendations>
		<index_history_nvp>2015-02-10=450;2015-02-11=350;2015-02-12=350;2015-02-13=200;2015-02-14=100;2015-02-15=0;2015-02-16=0</index_history_nvp>
		<index_history_csv>Categories;2015-02-10;2015-02-11;2015-02-12;2015-02-13;2015-02-14;2015-02-15;2015-02-16#Serie 1;450;350;350;200;100;0;0</index_history_csv>
		<index_history_xml>&lt;chart_data&gt;
&lt;categories&gt;
&lt;title&gt;Date&lt;/title&gt;
&lt;values&gt;
&lt;value&gt;2015-02-10&lt;/value&gt;
&lt;value&gt;2015-02-11&lt;/value&gt;
&lt;value&gt;2015-02-12&lt;/value&gt;
&lt;value&gt;2015-02-13&lt;/value&gt;
&lt;value&gt;2015-02-14&lt;/value&gt;
&lt;value&gt;2015-02-15&lt;/value&gt;
&lt;value&gt;2015-02-16&lt;/value&gt;
&lt;/values&gt;
&lt;/categories&gt;
&lt;series&gt;
&lt;serie&gt;
&lt;title&gt;Index&lt;/title&gt;
&lt;values&gt;
&lt;value&gt;450&lt;/value&gt;
&lt;value&gt;350&lt;/value&gt;
&lt;value&gt;350&lt;/value&gt;
&lt;value&gt;200&lt;/value&gt;
&lt;value&gt;100&lt;/value&gt;
&lt;value&gt;0&lt;/value&gt;
&lt;value&gt;0&lt;/value&gt;
&lt;/values&gt;
&lt;/serie&gt;
&lt;/series&gt;
&lt;/chart_data&gt;</index_history_xml>
	</WeeklyReport>
	<WeeklyReport>
		<badge_number>123457</badge_number>
		<email>svinchon@corp.com</email>
		<first_name>Dmitry</first_name>
		<last_name>Etin</last_name>
		<gender>male</gender>
		<week_start_date>2015-02-09</week_start_date>
		<recomendations>
			<recomendation>
				<!-- 0 to N occurrences -->
				<value>80</value>
				<!-- percentage, can be more than 100% => if so template charts need to be adjusted -->
				<label>Steps</label>
				<color>RGB value</color>
				<!-- it currently take an hex value like FF2200 but it seems to me that it would make more sense to let the choice be made at the template level or and indicator should also be provided to change the background image -->
				<text>Do more steps</text>
			</recomendation>
			<recomendation>
				<value>100</value>
				<label>Water</label>
				<color>RGB value</color>
				<text>Water drinking was great</text>
				<!-- did you mean "keep drinking the same way"?  -->
			</recomendation>
		</recomendations>
		<index_history_nvp>2015-02-10=0;2015-02-11=0;2015-02-12=0;2015-02-13=0;2015-02-14=100;2015-02-15=0;2015-02-16=0</index_history_nvp>
		<index_history_csv>Categories;2015-02-10;2015-02-11;2015-02-12;2015-02-13;2015-02-14;2015-02-15;2015-02-16#Serie 1;0;0;0;0;100;0;0</index_history_csv>
		<index_history_xml>&lt;chart_data&gt;
&lt;categories&gt;
&lt;title&gt;Date&lt;/title&gt;
&lt;values&gt;
&lt;value&gt;2015-02-10&lt;/value&gt;
&lt;value&gt;2015-02-11&lt;/value&gt;
&lt;value&gt;2015-02-12&lt;/value&gt;
&lt;value&gt;2015-02-13&lt;/value&gt;
&lt;value&gt;2015-02-14&lt;/value&gt;
&lt;value&gt;2015-02-15&lt;/value&gt;
&lt;value&gt;2015-02-16&lt;/value&gt;
&lt;/values&gt;
&lt;/categories&gt;
&lt;series&gt;
&lt;serie&gt;
&lt;title&gt;Index&lt;/title&gt;
&lt;values&gt;
&lt;value&gt;0&lt;/value&gt;
&lt;value&gt;0&lt;/value&gt;
&lt;value&gt;0&lt;/value&gt;
&lt;value&gt;0&lt;/value&gt;
&lt;value&gt;100&lt;/value&gt;
&lt;value&gt;0&lt;/value&gt;
&lt;value&gt;0&lt;/value&gt;
&lt;/values&gt;
&lt;/serie&gt;
&lt;/series&gt;
&lt;/chart_data&gt;</index_history_xml>
	</WeeklyReport>
</WeeklyReports>
