=== svinchon/WellnessProgramXPression/xDWTemplates/Old/UsersSingleIndex.xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="user"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="user">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="external_id"/>
        <xs:element ref="index"/>
        <xs:element ref="username"/>
        <xs:element ref="weight"/>
        <xs:element ref="sports_activity"/>
        <xs:element ref="birth_date"/>
        <xs:element ref="email"/>
        <xs:element ref="gender"/>
        <xs:element ref="index_updated_at"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="id" type="xs:NCName"/>
  <xs:element name="external_id" type="xs:NMTOKEN"/>
  <xs:element name="index" type="xs:NCName"/>
  <xs:element name="username" type="xs:NCName"/>
  <xs:element name="weight" type="xs:decimal"/>
  <xs:element name="sports_activity" type="xs:integer"/>
  <xs:element name="birth_date" type="xs:date"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="gender" type="xs:NCName"/>
  <xs:element name="index_updated_at" type="xs:NMTOKEN"/>
</xs:schema>

=== svinchon/WellnessProgramXPression/xDWTemplates/UsersSingleIndex.xml
<?xml version="1.0"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UsersSingleIndex.xml.xsd">
	<user>
		<id>P5zCrwdJ3giubpwVX2qTrg</id>
		<external_id>foob123</external_id>
		<index>null</index>
		<username>foob_sssnsame</username>
		<weight>1.23</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1982-10-22</birth_date>
		<email>john+doe@example.com</email>
		<gender>female</gender>
		<index_updated_at>1418323947</index_updated_at>
	</user>
	<user>
		<id>O240MaGWkvSokGvmC7rYFA</id>
		<external_id>5656866-12</external_id>
		<index>null</index>
		<username>john_doe_exist</username>
		<weight>75.6667</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1900-01-31</birth_date>
		<email>john+doe@exampddddle.com</email>
		<gender>female</gender>
		<index_updated_at>1418336854</index_updated_at>
	</user>
	<user>
		<id>RtmqIceU7PQBoCatBcekFQ</id>
		<external_id>5656866-12</external_id>
		<index>null</index>
		<username>john_doe</username>
		<weight>75.6667</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1900-01-31</birth_date>
		<email>john+doe25@example.com</email>
		<gender>female</gender>
		<index_updated_at>1418336926</index_updated_at>
	</user>
	<user>
		<id>eWisiXfUXL4INp0P6C5XpQ</id>
		<external_id>5656866-12</external_id>
		<index>null</index>
		<username>john_doe26</username>
		<weight>75.6667</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1900-01-31</birth_date>
		<email>john+doe26@example.com</email>
		<gender>female</gender>
		<index_updated_at>1418337143</index_updated_at>
	</user>
	<user>
		<id>zIyduUEmzYWusDG3ox807A</id>
		<external_id>5656866-12</external_id>
		<index>null</index>
		<username>john_doe27</username>
		<weight>75.6667</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1900-01-31</birth_date>
		<email>john+doe27@example.com</email>
		<gender>female</gender>
		<index_updated_at>1418337270</index_updated_at>
	</user>
	<user>
		<id>nXaR1ftkR5GGNPkgdBcrvg</id>
		<external_id>5656866-12</external_id>
		<index>null</index>
		<username>john_doe28</username>
		<weight>75.6667</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1900-01-31</birth_date>
		<email>john+doe28@example.com</email>
		<gender>female</gender>
		<index_updated_at>null</index_updated_at>
	</user>
	<user>
		<id>P7dbv8BIDbYssTQuTzoafA</id>
		<external_id>foob123</external_id>
		<index>null</index>
		<username>foob_ssnames</username>
		<weight>1.23</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1982-10-22</birth_date>
		<email>john+do565@example.com</email>
		<gender>female</gender>
		<index_updated_at>null</index_updated_at>
	</user>
	<user>
		<id>yePbxNCeNmCCnzbAIrxoiQ</id>
		<external_id>foob123</external_id>
		<index>null</index>
		<username>foob_sssnames</username>
		<weight>1.23</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1982-10-22</birth_date>
		<email>john+do566@example.com</email>
		<gender>female</gender>
		<index_updated_at>null</index_updated_at>
	</user>
	<user>
		<id>uCXjopCG5QpJStbmke6S2w</id>
		<external_id>5656866-12</external_id>
		<index>null</index>
		<username>john_doea</username>
		<weight>75.6667</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1900-01-31</birth_date>
		<email>john+doea@exampddddle.com</email>
		<gender>female</gender>
		<index_updated_at>null</index_updated_at>
	</user>
	<user>
		<id>qCDSb2H1Ba4LHBgp4UNoPA</id>
		<external_id>085001</external_id>
		<index>null</index>
		<username>johndoe01</username>
		<weight>80</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1698-05-08</birth_date>
		<email>john.doe.01@gmail.com</email>
		<gender>male</gender>
		<index_updated_at>null</index_updated_at>
	</user>
	<user>
		<id>bM72yorOnhkIsQQlG82Pgw</id>
		<external_id>085002</external_id>
		<index>null</index>
		<username>johndoe02</username>
		<weight>80</weight>
		<sports_activity>2</sports_activity>
		<birth_date>1698-05-08</birth_date>
		<email>john.doe.02@gmail.com</email>
		<gender>male</gender>
		<index_updated_at>null</index_updated_at>
	</user>
</users>
